feat: add saga step of UserCreate
team-xquare/v1-authentication-service pull request #5
Opened 2022-04-28 23:53 UTC by jhhong0509

closed #4

2022-04-29 09:38 UTC, leeseojune53 requested changes

2022-04-29 09:38 UTC, leeseojune53 commented on authentication-infrastructure/src/main/kotlin/com/xquare/authentication/v1authenticationservice/outbox/OutboxEntity.kt
> +
@Entity!

2022-05-02 23:07 UTC, jhhong0509 commented on authentication-infrastructure/src/main/kotlin/com/xquare/authentication/v1authenticationservice/outbox/OutboxEntity.kt
> +
아 이거 R2DBC는 `@Table`이 `@Entity`에용

2022-05-02 23:57 UTC, leeseojune53 approved these changes

2022-05-03 00:04 UTC, merged